development:
  adapter: postgresql
  encoding: UTF-8
  database: walkabout_development
  pool: 5
  host: localhost
  username: hildenton
  password: J1mdenton32686

test:
  adapter: postgresql
  encoding: UTF-8
  database: walkabout_test
  pool: 5
  host: localhost
  username: hildenton
  password: J1mdenton32686

production:
  adapter: postgresql
  encoding: UTF-8
  database: walkabout
  pool: 5
  host: localhost
  username: hildenton
  password: J1mdenton32686

