development:
  adapter: postgresql
  encoding: unicode
  database: walkabout_development
  pool: 5
  username: hildenton
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: walkabout_test
  pool: 5
  username: hildenton
  password:
